environment:
  matrix:
    - platform: x86
      PLATFORM_DIR: Win32
      PLATFORM_OUT: 32bit
    - platform: x64
      PLATFORM_DIR: x64
      PLATFORM_OUT: 64bit

os:
  - Visual Studio 2015

shallow_clone: true

configuration:
  - Release

before_build:
  - nuget restore

after_build:
  - 7z a wfs-extract-v%APPVEYOR_BUILD_VERSION%-windows-%PLATFORM_OUT%.zip %APPVEYOR_BUILD_FOLDER%\%PLATFORM_DIR%\Release\wfs-extract.exe
  - 7z a wfs-file-injector-v%APPVEYOR_BUILD_VERSION%-windows-%PLATFORM_OUT%.zip %APPVEYOR_BUILD_FOLDER%\%PLATFORM_DIR%\Release\wfs-file-injector.exe

artifacts:
  - path: wfs-extract-v%APPVEYOR_BUILD_VERSION%-windows-%PLATFORM_OUT%.zip
  - path: wfs-file-injector-v%APPVEYOR_BUILD_VERSION%-windows-%PLATFORM_OUT%.zip
