# Specify version format
version: 0.5.{build}

environment:
  matrix:
    - platform: x86
      PLATFORM_DIR: Win32
      PLATFORM_OUT: 32bit
    - platform: x64
      PLATFORM_DIR: x64
      PLATFORM_OUT: 64bit

os:
  - Visual Studio 2015

shallow_clone: true

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Release

before_build:
  - nuget restore

after_build:
  - 7z a wfs-extract-v%APPVEYOR_BUILD_VERSION%-windows-%PLATFORM_OUT%.zip %APPVEYOR_BUILD_FOLDER%\%PLATFORM_DIR%\Release\wfs-extract.exe
  - 7z a wfs-file-injector-v%APPVEYOR_BUILD_VERSION%-windows-%PLATFORM_OUT%.zip %APPVEYOR_BUILD_FOLDER%\%PLATFORM_DIR%\Release\wfs-file-injector.exe

artifacts:
  - path: wfs-extract-v%APPVEYOR_BUILD_VERSION%-windows-%PLATFORM_OUT%.zip
  - path: wfs-file-injector-v%APPVEYOR_BUILD_VERSION%-windows-%PLATFORM_OUT%.zip

# cache nuget directory
#cache:
#  - packages -> **\packages.config

#deploy:
#  tag: $(appveyor_repo_tag_name)
#  release: WFS Tools v$(appveyor_build_version)
#  description: WFS Tools v$(appveyor_build_version)
#  provider: GitHub
#  auth_token:
#    secure: zgIKVcub8f5Hp19YGIi0xwIaiLijYqzwF50SFD+83gpeLmZLHGZLonGEOlJAt6sc
#  artifact: /.*\.zip/
#  draft: false
#  prerelease: false
#  on:
#    branch: master
#    appveyor_repo_tag: true
